name: ESLint-Project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run prettier-check

      - name: Check for console.logs
        run: if grep -r "console.log" src ; then echo "Found console.log statements"; exit 1; fi

      - name: Attempt Build
        run: npm run testBuild
